# dnf install mysql-server -y
# systemctl enable mysqld 
# systemctl start  mysqld           
# mysql_secure_installation --set-root-pass ExpenseApp@1
# echo "** Mysql Installation Completed **"
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ COMPONENT }}"

- name: Install MySQL Server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Enable and start MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Set MySQL root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

- name: Print completion message
  ansible.builtin.debug:
    msg: "** {{ COMPONENT }} Installation Is Completed **"
